Repository Torchlight-SWE2324/ChatSQL, pull requests merged in 2024-01, with the labels that each got.

#17 [TCHL-81] Added installation guide
  ChatSQL/README.md
Labels: documentation, enhancement

#18 Added new dictionaries
  ChatSQL/JSON/auction.json
  ChatSQL/JSON/customer_order.json
  ChatSQL/JSON/dental_clinic.json
  ChatSQL/JSON/ecommerce_store.json
  ChatSQL/JSON/fitness_app.json
  ChatSQL/JSON/library.json
  ChatSQL/JSON/school_sys.json
  ChatSQL/JSON/swe_music.json
Labels: enhancement

#20 [TCHL-82] The input field will automatically become disabled if there are no more updated data dictionary
  ChatSQL/code/guiAdmin.py
  ChatSQL/code/guiUser.py
Labels: enhancement, RTB

#23 Reverted embedder
  ChatSQL/code/guiAdmin.py
  ChatSQL/code/guiEmbedder.py
Labels: enhancement
